---
- name: Установка пакетов OpenVPN (Debian)
  ansible.builtin.apt:
    name: openvpn
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов OpenVPN (RHEL-based)
  ansible.builtin.yum:
    name: openvpn
    state: present
  when: ansible_os_family == "RedHat"

- name: Создание директории для конфигурации OpenVPN-клиента
  ansible.builtin.file:
    path: /etc/openvpn
    state: directory
    mode: "0755"

- name: Копирование конфигурационного файла OpenVPN-клиента
  ansible.builtin.template:
    src: client.conf.j2
    dest: /etc/openvpn/client.conf
    mode: "0644"
  notify: Перезапуск OpenVPN

- name: Копирование ключей и сертификатов OpenVPN-клиента
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0600"
  with_items:
    - { src: "keys/ca.crt", dest: "/etc/openvpn/ca.crt" }
    - { src: "keys/client.crt", dest: "/etc/openvpn/client.crt" }
    - { src: "keys/client.key", dest: "/etc/openvpn/client.key" }
  notify: Перезапуск OpenVPN

- name: Проверка, запущен ли OpenVPN-клиент
  ansible.builtin.systemd:
    name: openvpn
    state: started
    enabled: yes

