---
- name: Установка OpenVPN для openvpn_client
  ansible.builtin.apt:
    name: openvpn
    state: present
  when: ansible_os_family == "Debian"

- name: Установка OpenVPN для openvpn_client (RHEL-based)
  ansible.builtin.yum:
    name: openvpn
    state: present
  when: ansible_os_family == "RedHat"

- name: Копирование конфигурации OpenVPN
  template:
    src: openvpn_client.conf.j2
    dest: /etc/openvpn/openvpn_client.conf
  notify: Перезапуск OpenVPN
