---
- name: Установка пакетов filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов filebeat (RHEL-based)
  ansible.builtin.yum:
    name: filebeat
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование filebeat
  template:
    src: templates/filebeat.conf.j2
    dest: /etc/filebeat/filebeat.conf
  notify: Перезапуск filebeat
