---
- name: Проверка установлен ли Filebeat (Debian)
  command: dpkg-query -W filebeat
  register: filebeat_check_debian
  changed_when: false
  failed_when: filebeat_check_debian.rc is defined and filebeat_check_debian.rc not in [0, 1]
  when: ansible_os_family == "Debian"

- name: Вывод результата проверки Filebeat (Debian)
  debug:
    var: filebeat_check_debian

- name: Добавление репозитория Elastic (Debian)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic-archive-keyring.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: elastic
  when: ansible_os_family == "Debian"

- name: Обновление кеша пакетов (Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Установка Filebeat (Debian)
  apt:
    name: filebeat
    state: present
  when: ansible_os_family == "Debian"

- name: Проверка установлен ли Filebeat (RHEL)
  command: rpm -q filebeat
  register: filebeat_check_rhel
  changed_when: false
  failed_when: filebeat_check_rhel.rc is defined and filebeat_check_rhel.rc not in [0, 1]
  when: ansible_os_family == "RedHat"

- name: Вывод результата проверки Filebeat (RHEL)
  debug:
    var: filebeat_check_rhel

- name: Добавление репозитория Elastic (RHEL)
  yum_repository:
    name: elastic
    description: Elastic repository for Filebeat
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Установка Filebeat (RHEL)
  yum:
    name: filebeat
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование Filebeat
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'
  register: restart_filebeat
  notify: Перезапуск filebeat

- name: Включение и запуск Filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: started
  when: ansible_os_family in ["Debian", "RedHat"]

