---
- name: Установка PostgreSQL (Ubuntu)
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Установка PostgreSQL (Fedora)
  dnf:
    name:
      - postgresql-server
      - postgresql
    state: present
    update_cache: yes
  when: ansible_distribution == "Fedora"

- name: Инициализация базы данных PostgreSQL (Fedora)
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION
  when: ansible_distribution == "Fedora"

- name: Включение и запуск PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

