---
- name: Установка пакетов grafana
  ansible.builtin.apt:
    name: grafana
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов grafana (RHEL-based)
  ansible.builtin.yum:
    name: grafana
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование grafana
  template:
    src: templates/grafana.conf.j2
    dest: /etc/grafana/grafana.conf
  notify: Перезапуск grafana
