---
- name: Установка пакетов apache
  ansible.builtin.apt:
    name: apache
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов apache (RHEL-based)
  ansible.builtin.yum:
    name: apache
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование apache
  template:
    src: templates/apache.conf.j2
    dest: /etc/apache/apache.conf
  notify: Перезапуск apache
