---
- name: Установка сервисов на сервер мониторинга (Server 1)
  hosts: monitoring_servers
  gather_facts: yes
  roles:
    - zabbix_server
    - zabbix_agent
    - grafana
    - filebeat
    - openvpn_server  # OpenVPN сервер
  tags: monitoring

- name: Установка сервисов на веб-сервер (Server 2)
  hosts: web_servers
  gather_facts: yes
  roles:
    - nginx
    - apache
    - php
    - zabbix_agent
    - filebeat
    - bind
    - mail
    - openvpn_client  # OpenVPN клиент
  tags: web

- name: Установка сервисов на сервер базы данных (Server 3)
  hosts: db_servers
  gather_facts: yes
  roles:
    - postgresql_server  # PostgreSQL 12
    - zabbix_agent
    - elk
    - openvpn_client  # OpenVPN клиент
  tags: database

# ✅ Добавляем новый блок для OpenVPN-клиентов на корректном уровне:
- name: Установка OpenVPN-клиента
  hosts: openvpn_clients
  gather_facts: yes
  roles:
    - openvpn_client
  tags: openvpn_client

