---
- name: Установить Zabbix Agent
  apt:
    name: zabbix-agent
    state: present
    update_cache: yes

- name: Создать конфигурационный файл Zabbix Agent
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Zabbix Agent

- name: Включить и запустить Zabbix Agent
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started

