---
- name: Установка пакетов elk
  ansible.builtin.apt:
    name: elk
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов elk (RHEL-based)
  ansible.builtin.yum:
    name: elk
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование elk
  template:
    src: templates/elk.conf.j2
    dest: /etc/elk/elk.conf
  notify: Перезапуск elk
