---
- name: Установка пакетов zabbix_agent
  ansible.builtin.apt:
    name: zabbix_agent
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов zabbix_agent (RHEL-based)
  ansible.builtin.yum:
    name: zabbix_agent
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование zabbix_agent
  template:
    src: templates/zabbix_agent.conf.j2
    dest: /etc/zabbix_agent/zabbix_agent.conf
  notify: Перезапуск zabbix_agent


