---
- name: Проверка установленного репозитория Zabbix (Debian)
  command: dpkg -l | grep zabbix-release || true
  register: zabbix_repo_check_debian
  changed_when: false
  failed_when: false
  when: ansible_os_family == "Debian"

- name: Вывод результата проверки репозитория Zabbix (Debian)
  debug:
    var: zabbix_repo_check_debian

- name: Добавление репозитория Zabbix (Debian)
  apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-1+debian_all.deb"
    state: present
  when:
    - ansible_os_family == "Debian"
    - zabbix_repo_check_debian is defined
    - zabbix_repo_check_debian.stdout is defined
    - "'zabbix-release' not in zabbix_repo_check_debian.stdout"

- name: Обновление кеша пакетов (Debian)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Установка пакетов Zabbix Agent (Debian)
  apt:
    name: zabbix-agent
    state: present
  when: ansible_os_family == "Debian"

- name: Проверка установленного репозитория Zabbix (RHEL)
  shell: "yum repolist | grep zabbix || true"
  register: zabbix_repo_check_rhel
  changed_when: false
  failed_when: false
  when: ansible_os_family == "RedHat"

- name: Добавление репозитория Zabbix (RHEL)
  yum:
    name: "https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm"
    state: present
  when:
    - ansible_os_family == "RedHat"
    - zabbix_repo_check_rhel is defined
    - zabbix_repo_check_rhel.stdout is defined
    - "'zabbix' not in zabbix_repo_check_rhel.stdout"

- name: Очистка и обновление кеша пакетов (RHEL)
  shell: "yum clean all && yum makecache"
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Установка пакетов Zabbix Agent (RHEL)
  yum:
    name: zabbix-agent
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурирование Zabbix Agent
  template:
    src: templates/zabbix_agent.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: Перезапуск Zabbix Agent

- name: Включение и запуск Zabbix Agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes

