---

- name: Включение обработчиков Zabbix
  import_tasks: ../handlers/main.yml


- name: Добавление репозитория Zabbix
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb"
  when: ansible_os_family == "Debian"

- name: Обновление списка пакетов
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Установка пакетов Zabbix Server
  ansible.builtin.apt:
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-sql-scripts
    state: present
  when: ansible_os_family == "Debian"

- name: Установка пакетов Zabbix Server (RHEL-based)
  ansible.builtin.yum:
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-agent
    state: present
  when: ansible_os_family == "RedHat"

- name: Конфигурация Zabbix
  ansible.builtin.template:
    src: templates/zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: Перезапуск Zabbix

